### DISCUSSION TITLE
docformatter in pre-commit doesn't use pyproject.toml

### DISCUSSION THREAD

**Discussion by suhanoves** [PyCQA/docformatter#89] [Q&A] [answered]
Hello!
I can't seem to get docformatter to read the `pyproject.toml` config file if it's set as part of the pre-commit.

.pre-commit-config.yaml:
```
- repo: https://github.com/myint/docformatter
  rev: v1.3.1
  hooks:
    - id: docformatter
      args: [--in-place]
```
pyproject.toml
```
[tool.docformatter]
recursive = true
wrap-summaries = 119
wrap-descriptions = 119
blank = true
```

Both files are in the root of the project. Other hooks successfully get settings from `pyproject.toml` - black, for example.
Any tips?
