### ISSUE TITLE
docformatter: error: unrecognized arguments: --config

### ISSUE THREAD

**Issue by lucasmtz** [PyCQA/docformatter#103]
Hi, 

I have been trying to configure docformatter using the **pyproject.toml** (this is especially useful for loading the config in pre-commit), but this argument does not exist in the latest release, although it exists in the GIT repo. Could you please check it out? 

Best regards.

**Comment by weibullguy** [comment]
You are correct.  Version 1.4 was released before the --config option was added.  I've only recently started helping out and haven't put a new v1.5 on PyPi yet.  I was waiting until I had cleaned up all the outstanding issues and PRs of the past few years to do that.  In pre-commit you can use a commit SHA in for the rev: field.  For example, the following will use the latest commit from last night:

```
- repo: https://github.com/PyCQA/docformatter
  rev: b108a208536f94da786211a28ea3bda4f55a04a4
  hooks:
    - id: docformatter
      additional_dependencies: [tomli]
      args: [--in-place, --config, ./pyproject.toml]
```

Let me know if that doesn't work.  There are two more old PRs I need to deal with and then I'll put a new release on PyPi.

**Comment by weibullguy** [comment]
You can also now use the v1.5.0-rc1 tag for the rev:

**Comment by mtvx** [comment]
@weibullguy Where does `docformatter` look up configs in 1.4? Or does it not support loading from config files at all (ie. you need to `--pass --some --args`)?

**Comment by weibullguy** [comment]
@mtvx there is no support for configuration files in 1.4.  You need to pass all the arguments on the command line.

**Comment by weibullguy** [comment]
Version 1.5.0 was released to PyPI.

**Comment by baggiponte** [comment]
I was using docformatter with pre-commit and got errors which I solved by using quotes:

```
# python docstring formatting
- repo: https://github.com/pycqa/docformatter
  rev: v1.5.0
  hooks:
  - id: docformatter
    args: ["--in-place", "--config", "./pyproject.toml"]
```
