### ISSUE TITLE
Release v1.5.0

### ISSUE THREAD

**Issue by weibullguy** [PyCQA/docformatter#106]
All PRs that have been open for the past several years have been merged.  Tag v1.5.0-rc1 is the latest.

To use v1.5.0-rc1 in your `.pre-commit-config.yaml`:
```
 - repo: https://github.com/PyCQA/docformatter
   rev: v1.5.0-rc1
   hooks:
     - id: docformatter
       additional_dependencies: [tomli]
       args: [--in-place, --config, ./pyproject.toml]
```

To install v1.5.0-rc1 using pip:
```
python -m pip install git+https://github.com/PyCQA/docformatter.git@v1.5.0-rc1
```
