### ISSUE TITLE
Option close-quotes-on-newline doesn't work with pre-commit

### ISSUE THREAD

**Issue by VDuchauffour** [PyCQA/docformatter#169]
Hello,
It seems that the option `close-quotes-on-newline` is not taken into account with pre-commit when it is declared in the pyproject.toml. For instance, if I have the following files:
`pyproject.toml`
```
[tool.docformatter]
close-quotes-on-newline = true
```
and `.pre-commit-config.yaml`
```
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args:
          [
            "--in-place",
            "--config",
            "pyproject.toml",
          ]
```
When I run `docformatter` on the following example, it works as expected:
```diff
 class CudaStatus:
     """Singleton class that contains informations relative to CUDA in the
-    current process."""
+    current process.
+    """
```
But the pre-commit pipeline will not fix the issue, unless I had a `"--close-quotes-on-newline",` in the args section in the pre-commit-config. Any ideas about this ?
I also think that the documentation should specify that this option fixes the pydocstyle D209 rule.
Thanks

**Comment by weibullguy** [comment]
@VDuchauffour this is similar to issue #172.  In both cases, I see you're using `docformatter-1.5.0`.  Could you try with `docformatter-1.6.0` to see if the problem persists?  Also, is that the only argument you set in `pyproject.toml` or is that the only  setting that is being ignored?

In all of my pre-commits, `docformatter` reads `pyproject.toml`, but the only thing I set is:
```
[tool.docformatter]
wrap-summaries = 88
wrap-descriptions = 88
```
I also don't quote the args in `.pre-commit-config.yaml` although it should work either way.
```
    - repo: https://github.com/PyCQA/docformatter
      rev: v1.6.0
      hooks:
        - id: docformatter
          additional_dependencies: [tomli]
          args: [--in-place, --config, ./pyproject.toml]
```
