### ISSUE TITLE
v1.7.1 - Newline Removed Between `:raises :` and `:param :` Documentation

### ISSUE THREAD

**Issue by rmartin16** [PyCQA/docformatter#216]
With v1.7.1, some newlines are being removed between `:raises :` and `:param :` documentation.

```diff
@@ -3,7 +3,6 @@ def search_delete(self, search_id=None, **kwargs):
     Delete a search job.
 
     :raises NotFound404Error: 
-
     :param search_id: ID of search to delete
     :return: None
     """
```

Although, this one is not reformatted:
```python
def rss_mark_as_read(self, item_path=None, article_id=None, **kwargs):
    """
    Mark RSS article as read. If article ID is not provider, the entire feed is marked
    as read.

    :raises NotFound404Error:

    :param item_path: path to item to be refreshed (e.g. ``Folder\\Subfolder\\ItemName``)
    :param article_id: article ID from :meth:`~RSSAPIMixIn.rss_items`
    :return: None
    """
```

Config:
```yaml
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.1
    hooks:
      - id: docformatter
        args: [--in-place, --pre-summary-newline, --black]
```

more examples: https://github.com/rmartin16/qbittorrent-api/pull/210
