### ISSUE TITLE
v1.7.1 - Quoted URL String Broken by Line Length Leaving Quote on Previous Line

### ISSUE THREAD

**Issue by rmartin16** [PyCQA/docformatter#218]
With v1.7.1, encountered a case of a quoted string at the line length being broken leaving the quote on the previous line.

Maybe the fact it's a URL is playing a role here...

```diff
     def make_project_url(self, bundle, app_name):
         """Construct a candidate project URL from the bundle and app name.
 
-        It's not a perfect guess, but it's better than having
-        "https://example.com".
+        It's not a perfect guess, but it's better than having "
+        https://example.com".
 
         :param bundle: The bundle identifier.
         :param app_name: The app name.
```

Config:
```yaml
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.1
    hooks:
      - id: docformatter
        args: [--in-place, --black]
```
