### ISSUE TITLE
Official release still broken with pre-commit (1.7.6?)

### ISSUE THREAD

**Issue by Eutropios** [PyCQA/docformatter#293]
Despite the commit modifying docformatter to allow for it to work with pre-commit 4.0, this commit has not been shipped as an official release. Is there any chance we could get a 1.7.6 release with the latest commit to allow us to continue using docformatter as a pre-commit hook with 4.0?

**Comment by GriceTurrble** [comment]
Just a note, all that's required for pre-commit's autoupdate is to make a new tag in the repo. If folks want to avoid a full release when there may not be changes to the underlying package, that is.

I propose a `v1.7.5-post1`?

As a workaround, folks can target `rev: "master"` in their configs.

**Comment by nfelt14** [comment]
@weibullguy, you were the one who merged the PR that fixed the issue on the master branch. Do you have permissions to create a new tag/release?

**Comment by jkanche** [comment]
> [@weibullguy](https://github.com/weibullguy), you were the one who merged the PR that fixed the issue on the master branch. Do you have permissions to create a new tag/release?

Hi, I was wondering if there's any updates on bumping the version?

**Comment by Niegazowana** [comment]
Hi, I see that there were some activity regarding this problem, are there no official news when the new release is planned?

**Comment by nfelt14** [comment]
Does anyone know who the primary maintainer of this package is so that we can get some progress made on this issue?

**Comment by mjspeck** [comment]
Seriously, how are PRs being merged, but no releases are happening?

**Comment by Pierre-Sassoulas** [comment]
It"s possible to use the commit sha instead of the version in pre-commit:
```
  - repo: https://github.com/PyCQA/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38 # Don't autoupdate until https://github.com/PyCQA/docformatter/issues/293 is fixed
    hooks:
      - id: docformatter
```
(But ``pre-commit autoupdate`` will use a tag even if it's less recent than the sha)
